export const banner = 'https://cdn.shopify.com/s/files/1/0607/2841/0296/files/Sub_Banner_Desktop_3_1fed8fa7-69c0-485e-a4b6-3b93cda5084c.jpg';

export const products = [
    {
        title: 'Kaos Oblong',
        description: 'Desc Kaos Oblong',
        price: '50000',
        discount: '25000',
        image: 'https://cdn.shopify.com/s/files/1/0607/2841/0296/products/Erigo-T-Shirt-Bill-Russel-Black-1.jpg',
        id: 0,
    },
    {
        title: 'Kaos Oblong 2',
        description: 'Desc Kaos Oblong 2',
        price: '50000',
        discount: '25000',
        image: 'https://cdn.shopify.com/s/files/1/0607/2841/0296/products/Erigo-T-Shirt-Maurice-Cheeks-Black-1.jpg',
        id: 1,
    },
    {
        title: 'Kaos Oblong 3',
        description: 'Desc Kaos Oblong 2',
        price: '50000',
        discount: '25000',
        image: 'https://cdn.shopify.com/s/files/1/0607/2841/0296/products/Erigo-T-Shirt-Maurice-Cheeks-White-3_360x.jpg',
        id: 2,
    },
    {
        title: 'Kaos Oblong 4',
        description: 'Desc Kaos Oblong 2',
        price: '50000',
        discount: '25000',
        image: 'https://cdn.shopify.com/s/files/1/0607/2841/0296/products/T-Shirt-Oversize-Espinosa-Olive-2-copy_360x.jpg',
        id: 3,
    },
    {
        title: 'Kaos Oblong 5',
        description: 'Desc Kaos Oblong 2',
        price: '50000',
        discount: '25000',
        image: 'https://cdn.shopify.com/s/files/1/0607/2841/0296/products/Hoodie-Kareem-Black-1_360x.jpg',
        id: 4,
    },

];

export const projects = [
    {
      title: 'HRMS',
      description: "HRMS is an ERP Application that I developed using Odoo framework, this application facilitates all in one solution for helps the HR on doing its Jobdesk. Plus this app is integration with Attendance Biometric Device",
        image: '/images/hrms.png',
        tags: ['Odoo', 'Pyhton', 'ERP'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 0,
    },
    {
      title: 'HRIS',
      description: "HRIS is an ERP Application that I developed using Odoo framework, this application is present for helps HR to view and manage the information about HR jobdesk. Plus this app is integration with Attendance Biometric Device",
        image: '/images/hris.png',
        tags: ['Odoo', 'Pyhton', 'ERP'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 1,
    },
    {
      title: 'Musfitatur App',
      description: "MusfitaturApp is a mobile application that I developed using the react native framework, this application facilitates bookings about travel, hajj, umrah.",
        image: '/images/musfiratur.png',
        tags: ['React Native'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 2,
    },
    {
      title: 'digiSchool',
      description:"digiSchool is a website-based application intended for al izhar schools, made with Nuxt JS, this application contains attendance, and eLearning for students.",
      image: '/images/digischool.png',
      tags: ['Nuxt Js', 'LoopBack 4', 'Node Js'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 3,
    },
    {
      title: 'eBos',
      description: "eBos is a website for administration and processing of subsidized funds for elementary schools, this application was made using Next JS and Redux Saga",
        image: '/images/ebos.png',
        tags: ['Next Js', 'Redux Saga'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 4,
    },
    {
      title: 'Smartfren Kiosk Dashboard',
      description: "Kiosk Dashboard is a website for managing smartfren kiosk vending machines, like upgrading the firmware, activating and deactivating vending machines. Built with Angular JS and Loopback 3",
      image: '/images/smartfren.png',
      tags: ['Angular Js', 'Loopback 3', 'Node Js'],
      source: 'https://google.com',
      visit: 'https://google.com',
      id: 5,
    },
  ];